[book]
authors = ["aerick"]
language = "en"
multilingual = false
src = "src"
title = "Lapwing for Beginners"

[output.html]
additional-css = ["theme/pagetoc.css", "theme/steno-viz.css", "theme/custom.css"]
additional-js = ["theme/pagetoc.js", "theme/steno-viz.js"]

[preprocessor.external-links]
